### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [distantcam/ConfigureAwait#13]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency ranged for Fody to be at least 2.0

 Please ping me if u need help

**Comment by cremor** [comment]
@distantcam Any ETA on when Fody 2.0 will be supported? I'd really like to update Fody in my project but ConfigureAwait.Fody currently prevents it.
